services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: hireme-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hireme
      - MONGO_INITDB_ROOT_PASSWORD=hireme_password
      - MONGO_INITDB_DATABASE=hireme
    volumes:
      - mongodb_data:/data/db
    networks:
      - hireme-network

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hireme-backend
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://hireme:hireme_password@mongodb:27017/hireme?authSource=admin
      - JWT_SECRET=hireme_jwt_secret_key_should_be_long_and_complex
      - JWT_EXPIRES_IN=30d
      - FRONTEND_URL=http://localhost:3000
      - SOCKET_URL=http://localhost:5001
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
      - OPENAI_MODEL=gpt-4o
      - HF_API_KEY=${HF_API_KEY:-your_huggingface_api_key_here}
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    networks:
      - hireme-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hireme-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:5001
      - VITE_SOCKET_URL=http://localhost:5001
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    networks:
      - hireme-network

# Volumes for data persistence
volumes:
  mongodb_data:
  backend_node_modules:
  frontend_node_modules:

# Networks
networks:
  hireme-network:
    driver: bridge
